version: '3.8'

services:
  muse-chat:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reloading
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true  # For better file watching on Docker
    stdin_open: true
    tty: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3